theme = "flexoki"

[editor]
mouse = false
middle-click-paste = false
cursorline = true
color-modes = true
trim-trailing-whitespace = true

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "â”†"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[editor.cursor-shape]
insert = "bar"
