theme = "flexoki"

[editor]
mouse = false
middle-click-paste = false
cursorline = true
color-modes = true
shell = ["fish", "-c"]
trim-trailing-whitespace = true
clipboard-provider = "pasteboard"

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "â”†"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
C-g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":reload-all"
]
