---
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  commit:
    signOff: true
  localBranchSortOrder: alphabetical
  remoteBranchSortOrder: alphabetical

gui:
  mouseEvents: false
