[settings]
experimental = true
verbose = false
jobs = 4
raw = false
pipx.uvx = true
python.uv_venv_auto = true

[tools]
aws = "latest"
glab = "latest"
go = "latest"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
hk = "latest"
just = "latest"
lazygit = "latest"
node = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:pyright" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
pnpm = "latest"
rust = "latest"
taplo = "latest"
